cc_binary(
    name = "app",
    srcs = [
        "SomeDataWithVectorOutput.hpp",
        "SomeDataWithVectorXmlSerializer.cpp",
        "SomeDataWithVectorXmlSerializer.hpp",
        "main.cpp",
    ],
    deps = [
        "//lib/base64",
        "//lib/persistency",
        "//lib/pugixml",
        "//lib/utility",
    ],
)
