cc_binary(
    name = "app",
    srcs = [
        "main.cpp",
        "DeviceAbstract.hpp",
        "TVDevice.hpp",
        "DVDDevice.hpp",
        "RemoteAbstract.hpp",
        "Remote.hpp",
    ],
)
