cc_library(
    name = "base64",
    srcs = [
        "Config.hpp",
        "Decoded.cpp",
        "Decoder.cpp",
        "Encoder.cpp",
        "Types.hpp",
    ],
    hdrs = [
        "Decoded.hpp",
        "Decoder.hpp",
        "Encoder.hpp",
    ],
    include_prefix = "base64",
    includes = ["."],
    visibility = [
        "//app:__pkg__",
    ],
)
