cc_library(
    name = "persistency",
    srcs = [
        "Persistency.hpp",
    ],
    hdrs = [
        "Serializer.hpp",
        "XmlPersistency.hpp",
    ],
    include_prefix = "persistency",
    includes = ["."],
    visibility = [
        "//app:__pkg__",
    ],
)
