cc_library(
    name = "pugixml",
    srcs = [
        "pugixml.cpp",
    ],
    hdrs = [
        "pugiconfig.hpp",
        "pugixml.hpp",
    ],
    include_prefix = "pugixml",
    visibility = [
        "//app:__pkg__",
    ],
)
