# This is the workflow to learn Github actions
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  steps:

  - uses: actions/checkout@v3
    
    run: |
      echo "Github name:  GITHUB_ACTION"
     
