# This is the workflow to learn Github actions
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
     
jobs:
  bash-example:
    runs-on: self-hosted
    steps:
      - name: Group of log lines
        run: |
            echo "gafoor"
